### ISSUE TITLE
로그인 DB

### ISSUE THREAD

**Issue by raysuhyunlee** [RaySuhyunLee/SNUCMS-Plus#1]
로그인 DB 만들기. 
`유저 id`, `패스워드`, `이름`, `이메일` 말고 또 뭐 있을까?

**Comment by sanha** [comment]
로그인 DB라는게 단순히 로그인에 필요한 DB를 말하는게 아니고 관리해야하는 고객 정보 전체를 말하는거야?

**Comment by raysuhyunlee** [comment]
아아아 유저디비!!ㅋㅋㅋ

**Comment by sanha** [comment]
그럼 한참 더 필요하지 않을까?
일단 팔로잉하는 강의들을 강의 DB에서 레퍼링해야 할 거고
이슈에 댓글 단 거는 이슈 디비에서 관리해주나?
일정들도 그렇고

**Comment by raysuhyunlee** [comment]
그러네 서로서로 다 레퍼런스하고 있어야겠구나

**Comment by kalaluthien** [comment]
유저 id(email이랑 통일?), pwd, 이름, 학번, 학교, 학부, [사진] <- 좀 세세해야 서로 태깅할 때 쓸 수 있을듯
- 소속 그룹, 내가 올린 이슈

**Comment by sanha** [comment]
코멘트 달았던 이슈에 코멘트달리는것도 알람하려면 이것도 저장해야 할 듯!
팔로잉하는 강의도 빠졌네.

**Comment by raysuhyunlee** [comment]
위키에서 반영하여 수정했슴당. 학부랑 학과는 따로 DB 안 파고 문자열로 처리해도 괜찮겠지?

**Comment by kalaluthien** [comment]
일단은 문자열로 처리하는 것이 차선인가...

**Comment by sanha** [comment]
ㅇㅇㅇㅇ 따로 테이블 가지고 있어야 할 이유가 있나 싶음.
