### ISSUE TITLE
Semantic-ui setting

### ISSUE THREAD

**Issue by kalaluthien** [RaySuhyunLee/SNUCMS-Plus#10]
다른 작업 시작하기 전에 Semantic-ui setting을 마쳐야 함. 설치하는 법은 아래에 있긴 한데...  
- http://semantic-ui.com/introduction/getting-started.html

예전 SNUCMS: https://github.com/simnalamburt/snucse.snucms/tree/master/vendor/assets 에서는 저렇게 vendor/assets에 딱 들어가서 설치 없이 쓸 수 있었는데, 이렇게 해야 안 꼬일 것 같음. 어떻게 하지?

**Comment by kalaluthien** [comment]
뭔가 예전 김젼의 commit에 이런 내용이 있음.  
https://github.com/simnalamburt/snucse.snucms/commit/f513169dc0417a5cb46a1af5b18e3ffc9fb8dcad

**Comment by raysuhyunlee** [comment]
고심 끝에 이거 쓰기로 함!
https://github.com/doabit/semantic-ui-sass
