### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by kalaluthien** [RaySuhyunLee/SNUCMS-Plus#101]
![](https://github.com/RaySuhyunLee/SNUCMS-Plus/blob/mockup_images/User%20Page.png)
[왜 이미지가 안 되지](https://github.com/RaySuhyunLee/SNUCMS-Plus/blob/mockup_images/User%20Page.png)

개인 프로필은 이거 쓰면 될 것 같네요
http://ko.gravatar.com/site/implement/

들어가야 할 항목 :
- [x] 개인 정보
- [x] 내가 구독하는 이슈 timeline
- [x] 개인 정보 수정 뷰

**Comment by sanha** [comment]
저는 user issue를 구현할게요
