### ISSUE TITLE
Course description placeholder problem

### ISSUE THREAD

**Issue by raysuhyunlee** [RaySuhyunLee/SNUCMS-Plus#103]
Course description 수정 버튼을 누르면 원래 있던 정보가 날아가고 "강의 설명을 작성해주세요" placeholder가 뜹니다.

**Comment by kalaluthien** [comment]
Course description에 markdown render를 적용하는 건 어떤가요?

**Comment by raysuhyunlee** [comment]
Markdown 적용하겠습니다
