### ISSUE TITLE
Mockup 및 Structure 수정

### ISSUE THREAD

**Issue by kalaluthien** [RaySuhyunLee/SNUCMS-Plus#13]
1) Main controller -> Home controller 명칭 변경
2) Group controller 생성
3) User(profile) page 레이아웃 수정 + Subscribes(내가 구독하고 있는 이슈 알림) / My issues(내가 발제한 이슈 목록)

**Comment by kalaluthien** [comment]
2) Group controller는 삭제합니다.

**Comment by kalaluthien** [comment]
Mock up 이거 유효기간 만료... 으어어어어어어어어

**Comment by sanha** [comment]
Course mockup에 있는 timeline은 필요치 않다고 판단되어 삭제하기로 결정하였습니다.

**Comment by raysuhyunlee** [comment]
이 이슈 끝났나요? 닫아도 될까요?ㅋㅋ
