### ISSUE TITLE
Issue tagging 정책 및 구현

### ISSUE THREAD

**Issue by sanha** [RaySuhyunLee/SNUCMS-Plus#14]
Issue를 열 때 태그를 다는 기능을 제공해야 함.

1)  미리 정해진 태그 중에 선택할 수 있게 할 것
2)  해당 태그를 단 이슈만 볼 수 있게 할 것

정도를 얘기한 것 같은데, 어떤 태그가 있을 지, 추가적으로 필요한 기능은 없는지 정리합시다.

**Comment by kalaluthien** [comment]
상위 태그: Project, Assignment, Quiz, Exam, Lab
하위 태그는 할지 말지 생각해봅시다.

**Comment by sanha** [comment]
Question, Debate(?), Report

**Comment by raysuhyunlee** [comment]
http://semantic-ui.com/modules/dropdown.html#search-dropdown
http://semantic-ui.com/behaviors/api.html

**Comment by kalaluthien** [comment]
Notice도 추가해주세요.

**Comment by sanha** [comment]
@kalaluthien 태그는 seed에 추가만 해 주시면 됩니다
