### ISSUE TITLE
로그인 폼 만들기

### ISSUE THREAD

**Issue by raysuhyunlee** [RaySuhyunLee/SNUCMS-Plus#2]
로그인 화면을 따로 만들까? 요즘에는 보통 팝업이나 임베드 방식으로 안 하고 별도의 로그인 창으로 이동하는 방식을 많이 쓰는 것 같던데 ㅋㅋㅋ 찾아보면 레일즈 로그인 기능 라이브러리 있을텐데 그런거 쓰는것도 좋을듯!

**Comment by sanha** [comment]
음 우선 라이브러리부터 찾아봐야겠지만 팝업방식은 진짜별로인것같고 새창으로 이동하거나 그냥 네이버처럼 ID PW란에 입력해서 들어갈 수 있게 하는게 좋을듯. 이게 수현이가 말한 임베드 방식이야?

**Comment by raysuhyunlee** [comment]
ㅇㅇ페이지 안에 끼여있는게 임베드!
https://github.com/plataformatec/devise
https://github.com/binarylogic/authlogic
http://blog.teamtreehouse.com/10-must-have-ruby-gems

https://github.com/NoamB/sorcery 얘는 단순한 로그인 기능에 적합한 가벼운 라이브러리인듯

**Comment by kalaluthien** [comment]
devise 저게 원래 SNUCMS에서 썼던 거야

**Comment by raysuhyunlee** [comment]
좋아 저걸로 가자(?)
2016. 3. 14. 01:26에 "김형모" notifications@github.com님이 작성:

**Comment by raysuhyunlee** [comment]
그러면 일단 devise로 해봅시다. 이번 이슈에서는 로그인 폼과 로그인되었는지 체크하는 토큰 기능정도 구현하면 될듯!
