### ISSUE TITLE
Issue feature 구현하기

### ISSUE THREAD

**Issue by sanha** [RaySuhyunLee/SNUCMS-Plus#22]
갈 길이 멉니다

**Comment by kalaluthien** [comment]
:tada:

**Comment by raysuhyunlee** [comment]
👍

**Comment by sanha** [comment]
# 앞으로 할 일

### 빨리 할 일
- ~~comment model 만든 후 issue에 종속시키기~~
- issue tagging
- ~~작성과 코멘트할 때 LaTeX, Markdown 지원~~
- ~~위키로 링크~~
- ~~이슈로 링크~~

### 천천히 할 일
- ~~group~~, user 추가되는 대로 대응하는 기능 지원
- 공통 Layout 씌우기
- html 예쁘게
- ~~user 연동~~

**Comment by sanha** [comment]
issue editing과 comment editting은 github처럼고 js로만 지원할 예정이므로, edit은 freezing합니다.

**Comment by kalaluthien** [comment]
Course가 구현이 되면, url에서 course 부분에서는 :id 대신 :title을 받도록 고쳐야 합니다.

**Comment by sanha** [comment]
~~라우팅 수정이 아주 뭣같겠지만, 노가다로 해결하겠습니다.~~
~~노가다로 때우리라!~~
#46 에서 :course_id를 유지하기로 결정하였습니다.

**Comment by sanha** [comment]
#56 을 통해 각 issue가 issue_id 뿐 아니라 parent가 갖는 issue 중 몇 번째 issue인지 나타내는 parent_issue_id를 갖도록 구현하였습니다.
이에 따라 issue의 url이 issue_id가 아니라 parent_issue_id가 됩니다.

**Comment by kalaluthien** [comment]
예제...?나 캡쳐를 볼 수 있을 까요

**Comment by sanha** [comment]
@kalaluthien  #56 에 자세한 예시를 적겠습니다.
이후 이에 대한 논의는 해당 이슈에서 진행합시다 :)

**Comment by sanha** [comment]
issue를 삭제 가능하게 할 것인지, 아니면 github처럼 close / reopen만 가능하게 할 것인지 정해야 할 듯 합니다.

**Comment by raysuhyunlee** [comment]
http://paginationjs.com/

이슈 전체보기에서 쓰기 좋을 듯한 라이브러리
