### ISSUE TITLE
account seed 추가

### ISSUE THREAD

**Issue by raysuhyunlee** [RaySuhyunLee/SNUCMS-Plus#30]
User Model에 테스트용 계정 하나 만들기

**Comment by kalaluthien** [comment]
이건 완료된 건가요?

**Comment by sanha** [comment]
풀리퀘를 받았는데 수현이가 아직 확인을 안했나봐요. 코멘트 상으로는 일단 완료된게 맞는 듯 하니 닫겠슴다
