### ISSUE TITLE
Home에 Timeline 기능 추가

### ISSUE THREAD

**Issue by kalaluthien** [RaySuhyunLee/SNUCMS-Plus#35]
더불어서 user page로 가는 버튼과 logout 버튼도 만들어주세요 >_<

**Comment by raysuhyunlee** [comment]
이슈에 아직 일정 등록 기능이 없으므로 타임라인 기능만 먼저 구현하겠습니다~

**Comment by sanha** [comment]
https://www.youtube.com/watch?v=2JdZcbjDD-s

**Comment by kalaluthien** [comment]
예전,,,SNUCMS,,,시절,,,js,,,code...
횐님께.도움이.될까..살짝.내려놓고...갑니다 ,,^^
즐거운...^^,,,개발,,,^^
[링크...^^](https://github.com/simnalamburt/snucse.snucms/blob/master/app/assets/javascripts/application.js)

**Comment by sanha** [comment]
장미꽃...한송이...놓고...갑니다,,,^^
@------>---------->-------------

**Comment by raysuhyunlee** [comment]
http://airbnb.io/infinity/

무한 스크롤 라이브러리

**Comment by raysuhyunlee** [comment]
https://github.com/thoughtbot/factory_girl

테스트용 시드 자동 생성기

**Comment by kalaluthien** [comment]
홈이 아닌 곳에서 스크롤을 해도 요청을 계속 보내는 현상
![image](https://cloud.githubusercontent.com/assets/6360552/15935603/cf455dc0-2ea2-11e6-89a8-35beebb2f718.png)

**Comment by sanha** [comment]
타임라인에서 이슈를 클릭해서 이슈로 이동할 수 있었으면 좋겠습니다!
