### ISSUE TITLE
course id -> course title로 변경

### ISSUE THREAD

**Issue by sanha** [RaySuhyunLee/SNUCMS-Plus#46]
제곧내

**Comment by sanha** [comment]
같은 title에 대해 여러 교수님이 개설하신 여러 course가 있을 수 있으므로, search key로 title은 부적합합니다.

**Comment by nolsigan** [comment]
http://idb.snu.ac.kr/images/a/a1/University_Database.pdf

maybe this could help designing schemas

**Comment by sanha** [comment]
@nolsigan Thx for help! But every rails model already has it's own ID :)
I'll refer to this pdf for entire schema.

**Comment by kalaluthien** [comment]
id로 그냥 하기로 했습니다.
