### ISSUE TITLE
Course 추가 페이지 만들기

### ISSUE THREAD

**Issue by raysuhyunlee** [RaySuhyunLee/SNUCMS-Plus#5]
깨끗하게 멋지게 자신있게!

**Comment by sanha** [comment]
issue feature를 구현하기 위해 rails에서 기본적으로 제공하는 틀을 이용하여 임시적으로 만들어 둔 상태입니다. 이 부분은 issue feature부분이 pull된 후 진행해주시면 좋겠네요~
