### ISSUE TITLE
Course feature 구현

### ISSUE THREAD

**Issue by sanha** [RaySuhyunLee/SNUCMS-Plus#50]
~~Schema 개선~~
이전 강의 연동

**Comment by sanha** [comment]
Schema를 개선하고 model을 연동하였습니다.
school과 professor, past_course 관련해서는 js가 필요하여 보류합니다.

**Comment by kalaluthien** [comment]
Seed를 추가했고, view 모양을 대충 다듬어둘 예정

**Comment by kalaluthien** [comment]
할 일 리스트를 정리해봅시다.
1. subscribe 기능 구현 - Ray가 하겠지
2. table에 추가할 사항
   1. 강의 상세 - 필요한가?
   2. links - website의 link를 들고있어야 함. 나중에 크롤링할 때도 사용하고.
   3. link를 사용자/관리자가 추가하고 삭제할 수 있어야 함.
   4. 어느 학기인지를 저장하고 있는 게 필요함. 지난 강의와의 연계에도 사용하고. created_at으로 해서는 안 됨.
3. 필요한 seed
   1. Professor가 있어야 course에 집어넣을 수 있음.
   2. 강의를 생성할 때 교수님을 검색하여 넣는 기능 추가해야 함.
   3. Null 교수님 추가해야 함. 전주식 하던가.
   4. School이 있어야 course에 집어넣을 수 있음.
   5. 마찬가지로 학교를 검색하여 넣는 기능 추가해야 함.
4. past_course와의 merge
   1. 총체적 노답. 구체적인 방안 논의가 필요. 일단 '학기'부터 저장을 해두고.
   2. 목업에서는 issues가 지난 issues로 이동할 수 있는 기능을 가지고 있었는데, 이게 course 자체에 필요하다고 봄. issue에서는 자기 parent course 것을 가져다 쓰고.
   3. Merge가 아니라 다음과 같이 하면 어떨까. 강의가 학기를 가지고 있다면, 그리고 현재 실제 학기가 그 학기보다 최근이라면, course page에 버튼이 생기는 것. 그걸 누르면 동일한 page가 학기만 바뀌어 복사해서 생기고, 이전 강의를 자동으로 연결하는 방식. 일단 자동화하는 건 '전부 뒤로 미루고' 구현부터 다 해두는게 좋을 것 같음.
5. course 자동 생성에 관하여.
   1. 정책을 바꿔서 이것도 사용자가 일단 직접 생성하는 것으로 해두자.
   2. 00X구분이 의미 없는 강의(수및연 등), 교수가 의미 없는 강의(아리세 등), 교수가 여럿인 강의, 이런 서비스가 필요 없는 강의(eTL만을 이용하거나, 아무 것도 이용하지 않으면서, 로드가 적은 강의) 등등을 적절히 사용자가 판단해서 관리할 수 있도록, 전부 Wiki같이 맡겨버려도 괜찮을 것 같음.

**Comment by sanha** [comment]
2.1. 강의 상세도 그냥 사용자에게 맡기는 편이 좋지 않을까요?
4. 우리는 다른 학기의 같은 강의를 merge하지 않습니다. issue tracker에서 past course의 issue로 이동하는 기능만 지원하고, 누적되어야 하는 정보는 wiki page에 저장하기로 했습니다. wiki page는 매 학기 새 강의가 열릴 때 마다 새로 열리지 않습니다.
5. 좋아요.

**Comment by kalaluthien** [comment]
2.1. 그러면 t.text :content 를 course에 추가하고, course edit page에서 professor, school, link, content 등을 수정할 수 있도록 해야 합니다. 강의명 빼고 다 수정할 수 있게 하면 되엤네요.
4. 단어 선택이 잘못 되었는데, merge가 아니라 inherit? course page도 학기가 지나면 새로 생성되는게 맞지 않는가요.

**Comment by sanha** [comment]
아 course 페이지는 그렇죠! 
인헤릿 관점에서 다시 읽으니 무슨말인지 알겠어요.
그러면 사용자가 코스를 생성하도록 하는데, past course를 지정하면 그 코스 페이지의 내용을 학기를 빼고 다 가져오고, 위키도 기존 위키에 링크시키면 되겠군요.

**Comment by kalaluthien** [comment]
네 그렇게 가도록 합시다.
그러면 할 일들을 순서에 따라서 다시 배열해볼게요어....

**Comment by kalaluthien** [comment]
~~Course Subscribe 기능 구현 - iss#51~~
~~1. Course title policy - “강의명(번호)” 로 일단 통일. Compiler(001)과 같음.~~
1. Course DB scheme 변경
   1. 강의상세(text) 추가 - (sugang.snu.ac.kr의 강의 소개에 나올 법한) 내용. 사용자가 수정하도록 함. Wiki의 경우는 교시와 같은 내용을 표기하지 않으므로, 없어서는 안 됨.
   2. 링크(string) 추가 - 이거는 여러 개 있을 수 있는데 어떻게 하나요? 크롤링 시에 이 링크들을 기준으로 긁어오도록 할 예정.
   3. 학기(string) 추가 - 더불어, Global한 최신 학기가 어딘가에 저장되어 있어야 함.
   4. 위키페이지이름(string) 추가 - Wiki에서는 강의 페이지를 Compiler(Egger)의 형식으로 저장하는 것이 자연스러움. Compiler(001) course와 Compiler(002) course가 모두 Egger 교수님의 강의일 수도 있고, 2016-1 Compiler(001)은 Egger 교수님, 2016-2 Compiler(001)은 이재진 교수님의 강의일 수도 있음. Compiler(001)을 parsing하고 Professor를 parsing해서 wiki page에서 검색하느니, 그냥 column 하나 추가해둡시다.
2. Edit Action 변경
   1. 강의상세 변경 기능 - Trivial
   2. Professor 추가 기능 - 존재하는 교수님만 추가할 수 있도록, 일단은 평문을 쳐서 그런 교수님이 존재하면 연결시키고, 그렇지 않으면 전주식을 연결시키도록 구현. 나중에는 검색해서 고르고, 없으면 Null을 넣을 수 있도록 구현.
   3. School 추가 기능 - 존재하는 학교만 추가할 수 있도록. 일단은 평문을 쳐서 그런 학교가 존재하면 연결시키고, 그렇지 않으면 서울대학교를 연결시키도록 구현. 나중에는 검색해서 고르고, 없으면 Null을 넣을 수 있도록 구현.
   4. 위키페이지이름 변경 기능 - Trivial
   5. 링크 추가/삭제 기능 - Trivial
3. Inherit past course 기능
   1. 현재 학기가 최신이 아닌 경우, 학기만 최신인 동일한 강의 페이지를 생성하고 (Website link를 제외한, 교수나 학교 연결 상태 동일) 최신 페이지의 past_courses에 기존의 페이지를 추가하도록 구현. 그 후, Course의 title 등을 edit할 수 있도록(001이 002가 되었다던가) edit page로 바로 redirect시키기.
   2. issues page는 새로 만들고, issues의 지난 issues에 기존 issues와 기존 issues의 지난 issues를 추가하도록 구현. (말이 복잡한가...)
4. Automative course generating - 00X구분이 의미 없는 강의(수및연 등), 교수가 의미 없는 강의(아리세 등), 교수가 여럿인 강의, 이런 서비스가 필요 없는 강의(eTL만을 이용하거나, 아무 것도 이용하지 않으면서, 로드가 적은 강의) 등등을 적절히 사용자가 판단해서 관리할 수 있도록, 전부 Wiki같이 맡겨버려도 괜찮을 것 같으므로, **구현하지 않음.**

이제 이것들을 서로 다른 issue로 빼면 되나

**Comment by kalaluthien** [comment]
Course 생성 시 Wiki의 link_page action을 AJAX 등으로 호출해주는 부분을 추가하세요.
#81
