### ISSUE TITLE
issue link

### ISSUE THREAD

**Issue by sanha** [RaySuhyunLee/SNUCMS-Plus#58]
issue 안에서 issue를 링크할 수 있도록 해야 합니다.
우선 github처럼 #숫자 했을 때 
courses/해당 course/issues/숫자 로 가게 할 예정.

**Comment by kalaluthien** [comment]
# 제목

#제목

github comment의 markdown renderer에서는 #뒤의 빈칸이 있어야 header인 것으로 인식하도록 되어있으니, 그에 맞추어 우리 것의 EXTENTIONS를 수정하는게 나을 것 같습니다..
![image](https://cloud.githubusercontent.com/assets/6360552/15570557/a10dddec-2371-11e6-830c-075d4c613f0b.png)
여기에 :space_after_headers 옵션을 추가해야 합니다.

**Comment by sanha** [comment]
/#(\d+)/로 구현하였기 때문에 #제목 등은 문제가 없습니다.

**Comment by sanha** [comment]
추가하겠습니다!

**Comment by sanha** [comment]
~~해당 번호의 이슈가 없을 때 링크로 렌더링하지 않도록 수정해야 함~~
~~link할 때 이슈 제목 보이도록 수정해야 함~~
수정했습니다

**Comment by sanha** [comment]
link할 때 이슈 제목 보이도록 수정해야 함
