### ISSUE TITLE
Test code 작성

### ISSUE THREAD

**Issue by sanha** [RaySuhyunLee/SNUCMS-Plus#60]
### Test할 동작

Sign in
Course 생성 편집 삭제
Course issue 생성
Course issue comment 추가 삭제
  Markdown, LaTeX 작동 확인
  Issue link, wiki page link 작동 확인
Wiki page 생성 편집 삭제
  Markdown, LaTeX 작동 확인
  wiki page link,  redirect 작동 확인
~~Sign out~~ 일해라 찰싹찰싹

**Comment by raysuhyunlee** [comment]
생각을 해 봤는데 자신이 구현한 파트 테스트코드를 자신이 작성하는게 더 좋지 않을까 합니다

**Comment by sanha** [comment]
음 네 그렇게하죠

**Comment by kalaluthien** [comment]
어떻게 작성하면 되나요

**Comment by raysuhyunlee** [comment]
먼 미래에 하겠습니다.
