### ISSUE TITLE
Wiki feature 구현하기

### ISSUE THREAD

**Issue by kalaluthien** [RaySuhyunLee/SNUCMS-Plus#8]
initial comment

**Comment by raysuhyunlee** [comment]
도움이 될 것 같은 플러그인(리비전 관리)

https://github.com/laserlemon/vestal_versions
https://github.com/airblade/paper_trail

**Comment by kalaluthien** [comment]
irwi와 gollum은 포기합니다

**Comment by raysuhyunlee** [comment]
직접 만드는 것을 추천합니다 :)

**Comment by kalaluthien** [comment]
# 앞으로 할 일

### 빨리 할 일
- ~~LaTeX 수식 지원~~
- ~~[[링크]]~~
- ~~redirect 문서~~
- ~~목차~~

### 가능하면 할 일
- ~~문서 간 계층~~
- ~~동시 수정 금지 - AJAX~~
- ~~미리 보기 기능 - AJAX~~
- ~~임시 저장 기능 - 안함~~

### 천천히 할 일
- ~~[리비전 관리](https://github.com/airblade/paper_trail)~~
- ~~주석[^1]~~
- ~~표?~~
- 메인의 토막글 등등 다양한 모아보기
- 공통 Layout(SNUCMS+ 마크, 검색창, 유저page, logout 등등) 씌우기
- seed 채우기(...)

---

[^1]: 이런 거

**Comment by kalaluthien** [comment]
위키 내 문서로 쉬운 링크 문법 구현. :tada: 
[[페이지명]]이라고 쓰면 [페이지명](http://**상대경로**/wiki/페이지명)으로 변환합니다.

---

[[페이지명|보여질 텍스트]] -> [보여질 텍스트](http://**상대경로**/wiki/페이지명) 이 기능은 지원해야 할까요? (거의 장난치는 용도로만 쓰이는데...)

**Comment by kalaluthien** [comment]
간단한 redirect 문법 구현. :tada: 
문서의 맨 위에 redirect [[페이지명]]을 끼워넣으면, 무조건 redirect 페이지로 인식함. (다른 내용 무시)

해결한 내용들!
- redirect loop (recursive) 금지: redirect를 연달아 이동하지 않습니다.
- redirect됨을 redirect된 page에 표시해주기: 상단에 표시됩니다.
- url에 따라 redirect 시키지 않고 보여주기: ?from=...이 붙으면 redirect시키지 않습니다. (물론 여기 헛점이 있기는 한데...)

**Comment by kalaluthien** [comment]
LaTeX 수식 기능 구현. :tada: 
문서의 $ ... $를 찾아서 내부의 수학 수식을 인터넷을 통해 svg로 변환하여 받아옴.
\$라고 쓰면 수식을 변환하지 않습니다. (물론 렌더링하기 전에 그냥 $로 바뀜)

**Comment by kalaluthien** [comment]
목차 기능 구현. :tada: 
자동으로 # header들을 읽어서 목차로 만들어줌 (근데 마크다운 list라서 좀 덜 예쁘긴 합니다)
근데 애초에 이 markdown render(= redcarpet)가 table-link를 만들기 위해 html id를 집어넣도록 설정을 해두었을 때에 영어 말고 인식을 제대로 못해요 \w으로 구현한 것 같음 : /\w/ - A word character ([a-zA-Z0-9_])
참고 : https://github.com/vmg/redcarpet/issues/538
그래서 목차에서 부분 문서로 이동하는 기능은 구현이 아직 안 되었습니다.

---

구현함. #20 참고.

**Comment by sanha** [comment]
[[페이지명|보여질 텍스트]] -> [보여질 텍스트](http://상대경로/wiki/페이지명) 있으면 좋지 않을까요? 장난치기 좋으니까...후후후

**Comment by kalaluthien** [comment]
TOC에서 #이 순서대로 제대로 붙지 않으면 에러가 납니다.

**Comment by sanha** [comment]
wiki 대문에 목차 문제와 관련한 튜토리얼이 있으면 좋겠네요!
Markdown 페이지가 따로 있어도 좋을 듯!

**Comment by kalaluthien** [comment]
Markdown page를 하나 만들고, wiki_page에 관리자용 삭제불가 on/off를 추가해야겠네요

**Comment by kalaluthien** [comment]
미리보기 기능 구현. :tada: 
AJAX를 사용하여 render된 결과를 붙여넣습니다.

---

리비전 기능 구현 :tada: 
Diff 기능은 지원하지 않고, 보는 기능과 복구 기능을 지원합니다.

**Comment by kalaluthien** [comment]
동시 수정 금지 기능 구현 :tada: 
AJAX를 (금지당할 때까지...) 주기적으로 보내 최신 버전이 바뀌었는지 check하여 수정 완료 버튼을 disable합니다.

덤으로, jQuery script를 실행하는 부분은 view로 옮기고 callback function만 wiki_page.js에 남겨두었습니다. #69

**Comment by kalaluthien** [comment]
<script> tag Escape하는 기능 구현 :tada: 

![image](https://cloud.githubusercontent.com/assets/6360552/15930098/f3043716-2e8b-11e6-9dde-ccf1933b6784.png)

...보안 이슈(?)

**Comment by kalaluthien** [comment]
주석(footnote)기능 추가 :tada: 
문법은 [나무위키 참고](https://namu.wiki/w/%EB%A7%88%ED%81%AC%EB%8B%A4%EC%9A%B4)

표(table) UI 향상 :tada: 

| First Header | Second Header |
| --- | --- |
| Content Cell | Content Cell |
| Content Cell | Content Cell |

이런 문법으로 작동을 하고, semantic-ui의 css를 사용함.
![image](https://cloud.githubusercontent.com/assets/6360552/15933094/4eeac61e-2e99-11e6-85cd-ead889a020f8.png)
