### ISSUE TITLE
강의 위키 제목

### ISSUE THREAD

**Issue by sanha** [RaySuhyunLee/SNUCMS-Plus#81]
자료구조
자료구조(강의)
자료구조(강의|문병로)

**Comment by kalaluthien** [comment]
이거는 두 군데서 작업해야 합니다.
- [x] Wiki - empty에서 `/.*(\(강의\)|\(강의|.*\))$/` 꼴의 제목을 생성하지 못하도록 하고, show에서 제목을 표시할 때 "(강의)"를 붙이지 않기. Course에서 생성/연결할 수 있도록 하는 action 추가(param: 제목, 링크, callback: 위키 제목). wiki_page에 type column 추가하기.
- [x] Course - 새로운 강의 생성할 때, 강의명 교수명을 입력하고 확인을 눌렀을 때 ajax 등을 보내서 wiki page를 생성/연결하는 action을 호출하고, 그 callback을 course column에 추가하기.
- course가 다 만들어져야 합니다.

**Comment by kalaluthien** [comment]
#91이 완료될 때까지 대기.

**Comment by kalaluthien** [comment]
Ajax말고 model에 method를 넣어서 구현함.
