### ISSUE TITLE
Crawler feature

### ISSUE THREAD

**Issue by kalaluthien** [RaySuhyunLee/SNUCMS-Plus#85]

**Comment by kalaluthien** [comment]
[Web Crawler](http://ruby.bastardsbook.com/chapters/web-crawling/)
[ActiveJob](http://edgeguides.rubyonrails.org/active_job_basics.html)
[Nokogiri](http://www.nokogiri.org/)
[SNUCMS](https://github.com/simnalamburt/snucse.snucms/blob/master/app/jobs/crawler_job.rb)

**Comment by kalaluthien** [comment]
- [x] Site model을 추가해야 비교 할 수 있음.
- [x] Course의 link를 모아와야 함.
- site model이 먼저 구축되어야 합니다. #91 
- [x] Issue를 등록할 수 있는 action을 호출해야 함.

**Comment by raysuhyunlee** [comment]
CrawlLog model(site model)에서 리비전 관리가 필요한가요? 일단 PaperTrail을 넣어놓긴 했습니다.

**Comment by kalaluthien** [comment]
@RaySuhyunLee  아니오, 마지막 것과만 비교하면 되므로 필요하지 않습니다.

**Comment by kalaluthien** [comment]
#91 이 완료될 때까지 대기

**Comment by kalaluthien** [comment]
rake tesk와 crontab을 이용합시다.
