### ISSUE TITLE
Course link for crawler

### ISSUE THREAD

**Issue by raysuhyunlee** [RaySuhyunLee/SNUCMS-Plus#91]
- [x] 링크 model `CrawlLog` 구현
- [x] 링크 추가/삭제 기능 - Trivial

**Comment by kalaluthien** [comment]
링크 하나하나가 site라는 model에 딸리도록 구현해주세여 #85

**Comment by raysuhyunlee** [comment]
생각해보니 이미 crawl_logs라는 table을 만들어놨습니다. 근데 만들다 말아서 아직 잘 안 될겁니다. 잘 되면 다시 말씀드리져  #85

**Comment by kalaluthien** [comment]
CrawlLog와 Course 사이의 dependency를 설정해주셔야합니다!

**Comment by sanha** [comment]
Course link마다 checkbox를 추가해서 체크된 애들만 크롤러를 만들어주세요

**Comment by kalaluthien** [comment]
Check된 애들만 크롤러가 크롤링하도록, db에 column을 추가해주세요~
